version: '3.8'

services:
  influence-monkey:
    build: .
    container_name: influence_api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URL: mongodb://root:root@mongo_new:27017/
    depends_on:
      - mongo_new
    networks:
      - app-network

  mongo_new:
    image: mongo
    container_name: mongo_new
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db
    networks:
      - app-network

volumes:
  mongodb_volume:

networks:
  app-network: